name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Build
        run:
          yarn build:ios_testflight

