lane :build do
    increment_build_number_in_plist(scheme: 'demo')
    gradle(
        task: "assemble",
        build_type: "Release"
    )
    appcenter_upload(
                api_token: "64e6e61ba91ea04a7677ceb672f113c3905bc931",
                owner_name: "yuanji.zhai-mdland.com",
                owner_type: "user",
                app_name: "demo_android",
                file: "./app/build/outputs/apk/release/app-release.apk",
                notify_testers: true
              )
end
