name: Build and dep

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Enter into work space
        run: cd / && cd /Users/yuanjizhai/Documents/project/demo
      - name: Get workspace path
        run: pwd
      - name: Build
        run: yarn build:ios_testflight
