name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    name: auto build
    runs-on: [self-hosted, macOS]

    steps:
      - name: message
        run: echo "before to build"
         
