name: Build and dep

on:
  push:
    branches: [ "main" ]

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./ios
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      - name: install bundler
        run: gem install bundler
      - name: install gems
        run: bundle install
      - name: pod install
        run: pod install
      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'testflight_build'

