name: Build and dep

on:
  push:
    branches: [ "main" ]

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ios
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: path
        run: pwd
      - name: build
        run: yarn build:ios_testflight

