name: Build and dep

on:
  push:
    branches: [ "main" ]

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
      - name: install
        run: bundle install
      - name: build
        run: bundle exec fastlane testflight_build

